version: "1.0"
services:
  gz-demomic-product:
    image: gz-demomic-product:0.0.1-SNAPSHOT
    container_name: gz-demomic-product
    ports:
      - "8088:8080"
    depends_on:
      - postgres
  gz-demomic-licence:
    image: gz-demomic-license:0.0.1-SNAPSHOT
    container_name: gz-demomic-license
    ports:
      - "8090:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: DEMOMIC_LICENSE,DEMOMIC_PRODUCT
      POSTGRES_USER: GZ_DEMOMIC
      POSTGRES_PASSWORD: GZ_DEMOMIC
    ports:
      - "5432:5432"